name: goreleaser

on: push
#on:
#  push:
#    # run only against tags
#    tags:
#      - '*'

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Set current datetime as env variable
        env:
          TZ: 'Asia/Tokyo' # タイムゾーン指定
        run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d.%H:%M:%S')" >> $GITHUB_ENV
      - name: Show current datetime
        run: echo ${{ env.CURRENT_DATETIME }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      #- run: git fetch --force --tags
      - run: git fetch --force --tags
      - name: Show current datetime
        run: git tag v${{ env.CURRENT_DATETIME }}_{{ .ShortCommit }}
      - uses: actions/setup-go@v4
        with:
          go-version: stable
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
